### ISSUE TITLE
Obnoxious white and black boxes

### ISSUE THREAD

**Issue by Elijas** [Trigstur/Quizlet-DarkSkin#1]
White part really strains eyes, can something be done about it?
![capture](https://user-images.githubusercontent.com/4084885/39671844-9849dc06-5128-11e8-9e0d-f510d00b5d52.PNG)

**Comment by Trigstur** [comment]
Hey Elijas first of all I want to thank you for using Quizlet Darkskin, I've put lots of love into making it and i'm glad you like it. I've fixed the issue > [https://github.com/Trigstur/Quizlet-DarkSkin/commit/57db10fc8492e7a63fd9774824f7ea60eb1e4c79](issue) and some bugs aswell, Thanks for notifying me of this bug, and please continue to do so

Kind regards 
Trigstur
