### ISSUE TITLE
White Flashcards Background (On Terms Page)

### ISSUE THREAD

**Issue by Raeffion** [Trigstur/Quizlet-DarkSkin#4]
For some reason, these flashcards appear on the terms page now. I don't mind it nearly as much as I do the white background. I'd fix it but I don't have time at the moment. If you don't get to it before I do then I'll issue a PR

![Example](https://user-images.githubusercontent.com/22381284/39949900-b726ec6e-5532-11e8-9efb-81e6516c0ace.png)

**Comment by Raeffion** [comment]
I believe you just have to be logged out, I didn't realize it until now.

**Comment by Trigstur** [comment]
Hey Raeffion, is your problem fixed now? If not please let me know and I'll try to fix it asap.

**Comment by Raeffion** [comment]
Yeah I have had no issues with this bug now
