### ISSUE TITLE
Broken background in Learn mode

### ISSUE THREAD

**Issue by ksilobait** [Trigstur/Quizlet-DarkSkin#6]
I have this problem with "Flashcards" question type only (in learn mode), multiple choice and written questions work fine
Browser: Opera 53; skin version: v0.2.5
![image](https://user-images.githubusercontent.com/17474821/41088219-23e2da52-6a69-11e8-9ad4-eb6599e51330.png)

**Comment by Trigstur** [comment]
Hey Ksilobait, thanks for reporting this ill fix it asap and include it into the next build, for the most recent update you can check the script here. Thanks for using the stylish if you have any other questions please ask

**Comment by Trigstur** [comment]
Hey @ksilobait the flipcards in learnmode should be working fine, as of now

Thanks for reporting

Sincerely,
Trigstur

![image](https://user-images.githubusercontent.com/11588132/45480455-5452ac80-b749-11e8-98e3-071325780909.png)
