### ISSUE TITLE
Odd Gradient on side bar of Learn Mode

### ISSUE THREAD

**Issue by githuuhb** [Trigstur/Quizlet-DarkSkin#7]
Everything runs perfectly but there are these white gradients off to the side that are quite disturbing in learn mode as seen from the picture below.
![sc](https://user-images.githubusercontent.com/46710471/51176000-28198900-18ff-11e9-9f19-b369847c1cbc.png)

**Comment by Trigstur** [comment]
Oh no! that sure doesn’t look as it is suppose to! Let me check up with the current build and see if I can fix it within this week!

Yours faithfully 

Coen

**Comment by Trigstur** [comment]
You are lucky! I checked up with the development build and I was able to fix it pretty easy. By adding the following code :

> 
> .ModeControls-blurTop,.ModeControls-blurBottom {
> 	background: transparent;
> }

[commit link](https://github.com/Trigstur/Quizlet-DarkSkin/commit/85cd25e06c15970852ac701b6e1ccdd51f5851cc)


The update will appear on stylish this hour, the version number will not update as I am updating it silently
